// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oicar.Dal;

namespace Oicar.Dal.Migrations
{
    [DbContext(typeof(OicarContext))]
    [Migration("20200514194532_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Oicar.Dal.Entities.CloudDbSQL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("AverageHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("BaskupSize")
                        .HasColumnType("integer");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Instance")
                        .HasColumnType("integer");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<int>("SQLServerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CloudSQL");
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExecutinPerRequestInMiliseconds")
                        .HasColumnType("integer");

                    b.Property<double>("ExecutionsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<int>("MemorySizeInMB")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CloudFunction");
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("ReadOperationsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<double>("WriteOperationsPerMonth")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CloudStorage");
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("AverageHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("Core")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("InstanceNb")
                        .HasColumnType("integer");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<double>("Storage")
                        .HasColumnType("double precision");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CloudVM");
                });

            modelBuilder.Entity("Oicar.Dal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 5, 14, 21, 45, 31, 980, DateTimeKind.Local).AddTicks(2097),
                            FirstName = "Trolo",
                            LastName = "Trolic",
                            Modified = new DateTime(2020, 5, 14, 21, 45, 31, 981, DateTimeKind.Local).AddTicks(9129)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
