// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oicar.Dal;

namespace Oicar.Dal.Migrations
{
    [DbContext(typeof(OicarContext))]
    [Migration("20200526144545_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Oicar.Dal.Entities.CloudDbSQL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("AverageHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("BaskupSize")
                        .HasColumnType("integer");

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Instance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<int>("SQLServerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CloudSQL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 812, DateTimeKind.Local).AddTicks(6830),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 812, DateTimeKind.Local).AddTicks(6840),
                            Price = 45.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(640),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(660),
                            Price = 48.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 3,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(760),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(760),
                            Price = 41.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 4,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(760),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(770),
                            Price = 24.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 5,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(770),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(770),
                            Price = 37.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 6,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(780),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(780),
                            Price = 36.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 7,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(780),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(790),
                            Price = 27.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 8,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(790),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(790),
                            Price = 30.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 9,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(800),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(800),
                            Price = 31.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 10,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(800),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(810),
                            Price = 21.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 11,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(810),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(810),
                            Price = 20.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 12,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(820),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(820),
                            Price = 18.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 13,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(820),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(830),
                            Price = 30.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 14,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(830),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(830),
                            Price = 27.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 15,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(840),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(840),
                            Price = 28.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 16,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(840),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(840),
                            Price = 38.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 17,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(850),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(850),
                            Price = 39.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 18,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(850),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(860),
                            Price = 40.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 19,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(860),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(860),
                            Price = 48.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 20,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(870),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(870),
                            Price = 47.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 21,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(870),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(880),
                            Price = 52.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 22,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 0,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(880),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(880),
                            Price = 59.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 23,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 2,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(910),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(910),
                            Price = 56.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 24,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 1,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(910),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(910),
                            Price = 57.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 25,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 0,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(920),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(920),
                            Price = 59.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 26,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 2,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(920),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(930),
                            Price = 56.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 27,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 1,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(930),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 813, DateTimeKind.Local).AddTicks(930),
                            Price = 84.0,
                            Ram = 32,
                            SQLServerType = 0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExecutinPerRequestInMiliseconds")
                        .HasColumnType("integer");

                    b.Property<double>("ExecutionsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<int>("MemorySizeInMB")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CloudFunction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(6020),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 10000.0,
                            MemorySizeInMB = 10000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(6040),
                            Price = 10.0
                        },
                        new
                        {
                            Id = 2,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8200),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 10000.0,
                            MemorySizeInMB = 10000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8220),
                            Price = 12.0
                        },
                        new
                        {
                            Id = 3,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8260),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 100000.0,
                            MemorySizeInMB = 10000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8270),
                            Price = 9.0
                        },
                        new
                        {
                            Id = 4,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8270),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 50000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8270),
                            Price = 18.0
                        },
                        new
                        {
                            Id = 5,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8280),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 50000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8280),
                            Price = 20.0
                        },
                        new
                        {
                            Id = 6,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8280),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 50000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8290),
                            Price = 22.0
                        },
                        new
                        {
                            Id = 7,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8290),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 250000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8290),
                            Price = 44.0
                        },
                        new
                        {
                            Id = 8,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8290),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 250000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8300),
                            Price = 41.0
                        },
                        new
                        {
                            Id = 9,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8300),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 250000,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 810, DateTimeKind.Local).AddTicks(8300),
                            Price = 39.0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("ReadOperationsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<double>("WriteOperationsPerMonth")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CloudStorage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(5330),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(5350),
                            Price = 100.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 2,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7560),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7580),
                            Price = 54.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 16.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 3,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7630),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7630),
                            Price = 60.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 32.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 4,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7640),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7640),
                            Price = 68.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 5,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7640),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7650),
                            Price = 88.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 6,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7650),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7650),
                            Price = 98.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 7,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7660),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7660),
                            Price = 112.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 8,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7660),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7670),
                            Price = 122.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 9,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7670),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7670),
                            Price = 135.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 10,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7670),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7680),
                            Price = 156.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 11,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7680),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7680),
                            Price = 159.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 12,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7690),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7690),
                            Price = 76.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 13,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7690),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7700),
                            Price = 73.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 14,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7700),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7700),
                            Price = 79.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 15,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7710),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7710),
                            Price = 86.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 16,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7710),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7710),
                            Price = 99.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 17,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7720),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7720),
                            Price = 113.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 18,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7720),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7730),
                            Price = 183.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 19,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7730),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7730),
                            Price = 180.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 20,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7730),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7740),
                            Price = 167.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 21,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7740),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7740),
                            Price = 169.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 22,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7750),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7750),
                            Price = 160.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 23,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7750),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7760),
                            Price = 183.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 24,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7760),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7760),
                            Price = 68.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 25,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7770),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7770),
                            Price = 78.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 26,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7770),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7770),
                            Price = 65.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 27,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7780),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7780),
                            Price = 78.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 28,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7780),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7790),
                            Price = 66.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 29,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7790),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7790),
                            Price = 46.0,
                            ReadOperationsPerMonth = 125000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 125000.0
                        },
                        new
                        {
                            Id = 30,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7800),
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 806, DateTimeKind.Local).AddTicks(7800),
                            Price = 55.0,
                            ReadOperationsPerMonth = 125000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 125000.0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("AverageHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<int>("Core")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("InstanceNb")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<double>("Storage")
                        .HasColumnType("double precision");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CloudVM");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(4790),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(4810),
                            OperatingSystem = 1,
                            Price = 1500.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(8970),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(8990),
                            OperatingSystem = 1,
                            Price = 1250.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 3,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9090),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9090),
                            OperatingSystem = 0,
                            Price = 1650.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 4,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9100),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9100),
                            OperatingSystem = 0,
                            Price = 1400.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 5,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9100),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9110),
                            OperatingSystem = 1,
                            Price = 4000.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 6,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9110),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9110),
                            OperatingSystem = 1,
                            Price = 3800.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 7,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9120),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9120),
                            OperatingSystem = 0,
                            Price = 3600.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 8,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9120),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9130),
                            OperatingSystem = 0,
                            Price = 3750.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 9,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9130),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9130),
                            OperatingSystem = 1,
                            Price = 850.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 10,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9140),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9140),
                            OperatingSystem = 1,
                            Price = 900.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 11,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9140),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9140),
                            OperatingSystem = 0,
                            Price = 887.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 12,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9150),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9150),
                            OperatingSystem = 0,
                            Price = 800.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 13,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9160),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9160),
                            OperatingSystem = 1,
                            Price = 1509.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 14,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9160),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9170),
                            OperatingSystem = 1,
                            Price = 1350.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 15,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9170),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9170),
                            OperatingSystem = 0,
                            Price = 1652.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 16,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9180),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9180),
                            OperatingSystem = 0,
                            Price = 1389.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 17,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9200),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9200),
                            OperatingSystem = 1,
                            Price = 3800.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 18,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9210),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9210),
                            OperatingSystem = 1,
                            Price = 3901.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 19,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9210),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9210),
                            OperatingSystem = 0,
                            Price = 3609.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 20,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9220),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9220),
                            OperatingSystem = 0,
                            Price = 3759.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 21,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9230),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9230),
                            OperatingSystem = 1,
                            Price = 950.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 22,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9230),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9230),
                            OperatingSystem = 1,
                            Price = 909.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 23,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9240),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9240),
                            OperatingSystem = 0,
                            Price = 869.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 24,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9240),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9250),
                            OperatingSystem = 0,
                            Price = 809.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 25,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9250),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9250),
                            OperatingSystem = 1,
                            Price = 1499.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 26,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9260),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9260),
                            OperatingSystem = 1,
                            Price = 1359.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 27,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9270),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9270),
                            OperatingSystem = 0,
                            Price = 1656.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 28,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9270),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9270),
                            OperatingSystem = 0,
                            Price = 1379.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 29,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9280),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9280),
                            OperatingSystem = 1,
                            Price = 3790.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 30,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9280),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9290),
                            OperatingSystem = 1,
                            Price = 3911.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 31,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9290),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9290),
                            OperatingSystem = 0,
                            Price = 3619.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 32,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9300),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9300),
                            OperatingSystem = 0,
                            Price = 3659.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 33,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9310),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9310),
                            OperatingSystem = 1,
                            Price = 944.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 34,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9310),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9320),
                            OperatingSystem = 1,
                            Price = 911.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 35,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9320),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9320),
                            OperatingSystem = 0,
                            Price = 919.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 36,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9330),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 809, DateTimeKind.Local).AddTicks(9330),
                            OperatingSystem = 0,
                            Price = 821.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 796, DateTimeKind.Local).AddTicks(6870),
                            Email = "admin@test.com",
                            FirstName = "Admin",
                            LastName = "Ad",
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 803, DateTimeKind.Local).AddTicks(5360),
                            Password = "Admin!123"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 5, 26, 16, 45, 44, 803, DateTimeKind.Local).AddTicks(8160),
                            Email = "test@test.com",
                            FirstName = "Test",
                            LastName = "Testic",
                            Modified = new DateTime(2020, 5, 26, 16, 45, 44, 803, DateTimeKind.Local).AddTicks(8190),
                            Password = "Test!123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
