// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oicar.Dal;

namespace Oicar.Dal.Migrations
{
    [DbContext(typeof(OicarContext))]
    partial class OicarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Oicar.Dal.Entities.CloudDbSQL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'28', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("AverageHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("BaskupSize")
                        .HasColumnType("integer");

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Instance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<int>("SQLServerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CloudSQL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 674, DateTimeKind.Local).AddTicks(2420),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 674, DateTimeKind.Local).AddTicks(2450),
                            Price = 45.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(70),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(100),
                            Price = 48.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 3,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(280),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(290),
                            Price = 41.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 4,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(300),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(300),
                            Price = 24.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 5,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(310),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(320),
                            Price = 37.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 6,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(330),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(330),
                            Price = 36.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 7,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(340),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(350),
                            Price = 27.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 8,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(350),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(360),
                            Price = 30.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 9,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(370),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(370),
                            Price = 31.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 10,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(380),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(380),
                            Price = 21.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 11,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(390),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(400),
                            Price = 20.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 12,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(410),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(410),
                            Price = 18.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 13,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(420),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(420),
                            Price = 30.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 14,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(430),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(440),
                            Price = 27.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 15,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(440),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(450),
                            Price = 28.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 16,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(460),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(460),
                            Price = 38.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 17,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(470),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(470),
                            Price = 39.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 18,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(480),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(490),
                            Price = 40.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 19,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(490),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(500),
                            Price = 48.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 20,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(510),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(510),
                            Price = 47.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 21,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(520),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(520),
                            Price = 52.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 22,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 0,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(530),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(540),
                            Price = 59.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 23,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 2,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(540),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(550),
                            Price = 56.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 24,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 1,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(560),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(560),
                            Price = 57.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 25,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 0,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(570),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(580),
                            Price = 59.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 26,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 2,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(580),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(590),
                            Price = 56.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 27,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 1,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(600),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 675, DateTimeKind.Local).AddTicks(600),
                            Price = 84.0,
                            Ram = 32,
                            SQLServerType = 0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'13', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExecutinPerRequestInMiliseconds")
                        .HasColumnType("integer");

                    b.Property<double>("ExecutionsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<int>("MemorySizeInMB")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CloudFunction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(2700),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 10000.0,
                            MemorySizeInMB = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(2740),
                            Price = 10.0
                        },
                        new
                        {
                            Id = 2,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7110),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 10000.0,
                            MemorySizeInMB = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7130),
                            Price = 12.0
                        },
                        new
                        {
                            Id = 3,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7230),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 100000.0,
                            MemorySizeInMB = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7240),
                            Price = 9.0
                        },
                        new
                        {
                            Id = 4,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7250),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 10,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7250),
                            Price = 18.0
                        },
                        new
                        {
                            Id = 5,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7260),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 10,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7270),
                            Price = 20.0
                        },
                        new
                        {
                            Id = 6,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7270),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 10,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7280),
                            Price = 22.0
                        },
                        new
                        {
                            Id = 7,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7280),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 100,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7290),
                            Price = 44.0
                        },
                        new
                        {
                            Id = 8,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7300),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 100,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7300),
                            Price = 41.0
                        },
                        new
                        {
                            Id = 9,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7340),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 100,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7350),
                            Price = 39.0
                        },
                        new
                        {
                            Id = 10,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7350),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 1000,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7360),
                            Price = 44.0
                        },
                        new
                        {
                            Id = 11,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7370),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 1000,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7370),
                            Price = 41.0
                        },
                        new
                        {
                            Id = 12,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7380),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 1000,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 669, DateTimeKind.Local).AddTicks(7380),
                            Price = 39.0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'31', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("ReadOperationsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<double>("WriteOperationsPerMonth")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CloudStorage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(2720),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(2780),
                            Price = 100.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 2,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7200),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7230),
                            Price = 54.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 16.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 3,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7340),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7350),
                            Price = 60.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 32.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 4,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7360),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7360),
                            Price = 68.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 5,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7370),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7370),
                            Price = 88.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 6,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7380),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7390),
                            Price = 98.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 7,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7390),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7400),
                            Price = 112.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 8,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7410),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7410),
                            Price = 122.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 9,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7420),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7420),
                            Price = 135.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 10,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7430),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7430),
                            Price = 156.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 11,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7440),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7450),
                            Price = 159.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 12,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7450),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7460),
                            Price = 76.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 13,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7470),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7470),
                            Price = 73.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 14,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7480),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7480),
                            Price = 79.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 15,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7490),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7500),
                            Price = 86.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 16,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7500),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7510),
                            Price = 99.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 17,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7510),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7520),
                            Price = 113.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 18,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7530),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7530),
                            Price = 183.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 19,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7540),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7540),
                            Price = 180.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 20,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7550),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7560),
                            Price = 167.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 21,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7560),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7570),
                            Price = 169.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 22,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7570),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7580),
                            Price = 160.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 23,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7590),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7590),
                            Price = 183.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 24,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7600),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7600),
                            Price = 68.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 25,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7610),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7620),
                            Price = 78.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 26,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7620),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7630),
                            Price = 65.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 27,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7630),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7640),
                            Price = 78.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 28,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7650),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7650),
                            Price = 66.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 29,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7660),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7660),
                            Price = 46.0,
                            ReadOperationsPerMonth = 125000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 125000.0
                        },
                        new
                        {
                            Id = 30,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7670),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 659, DateTimeKind.Local).AddTicks(7680),
                            Price = 55.0,
                            ReadOperationsPerMonth = 125000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 125000.0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'37', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("AverageHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<int>("Core")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("InstanceNb")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<double>("Storage")
                        .HasColumnType("double precision");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CloudVM");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 665, DateTimeKind.Local).AddTicks(6530),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 665, DateTimeKind.Local).AddTicks(6570),
                            OperatingSystem = 1,
                            Price = 1500.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5090),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5120),
                            OperatingSystem = 1,
                            Price = 1250.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 3,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5300),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5300),
                            OperatingSystem = 0,
                            Price = 1650.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 4,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5310),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5320),
                            OperatingSystem = 0,
                            Price = 1400.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 5,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5330),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5330),
                            OperatingSystem = 1,
                            Price = 4000.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 6,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5340),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5350),
                            OperatingSystem = 1,
                            Price = 3800.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 7,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5350),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5360),
                            OperatingSystem = 0,
                            Price = 3600.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 8,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5360),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5370),
                            OperatingSystem = 0,
                            Price = 3750.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 9,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5380),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5380),
                            OperatingSystem = 1,
                            Price = 850.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 10,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5390),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5400),
                            OperatingSystem = 1,
                            Price = 900.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 11,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5400),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5410),
                            OperatingSystem = 0,
                            Price = 887.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 12,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5420),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5420),
                            OperatingSystem = 0,
                            Price = 800.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 13,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5430),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5430),
                            OperatingSystem = 1,
                            Price = 1509.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 14,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5440),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5450),
                            OperatingSystem = 1,
                            Price = 1350.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 15,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5450),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5460),
                            OperatingSystem = 0,
                            Price = 1652.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 16,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5470),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5470),
                            OperatingSystem = 0,
                            Price = 1389.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 17,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5480),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5490),
                            OperatingSystem = 1,
                            Price = 3800.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 18,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5490),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5500),
                            OperatingSystem = 1,
                            Price = 3901.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 19,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5510),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5510),
                            OperatingSystem = 0,
                            Price = 3609.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 20,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5520),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5520),
                            OperatingSystem = 0,
                            Price = 3759.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 21,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5530),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5540),
                            OperatingSystem = 1,
                            Price = 950.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 22,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5540),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5550),
                            OperatingSystem = 1,
                            Price = 909.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 23,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5560),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5560),
                            OperatingSystem = 0,
                            Price = 869.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 24,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5570),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5570),
                            OperatingSystem = 0,
                            Price = 809.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 25,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5580),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5590),
                            OperatingSystem = 1,
                            Price = 1499.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 26,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5590),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5600),
                            OperatingSystem = 1,
                            Price = 1359.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 27,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5610),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5610),
                            OperatingSystem = 0,
                            Price = 1656.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 28,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5620),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5630),
                            OperatingSystem = 0,
                            Price = 1379.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 29,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5630),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5640),
                            OperatingSystem = 1,
                            Price = 3790.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 30,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5650),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5650),
                            OperatingSystem = 1,
                            Price = 3911.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 31,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5660),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5660),
                            OperatingSystem = 0,
                            Price = 3619.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 32,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5670),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5680),
                            OperatingSystem = 0,
                            Price = 3659.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 33,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5680),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5690),
                            OperatingSystem = 1,
                            Price = 944.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 34,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5700),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5700),
                            OperatingSystem = 1,
                            Price = 911.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 35,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5710),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5710),
                            OperatingSystem = 0,
                            Price = 919.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 36,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5720),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 666, DateTimeKind.Local).AddTicks(5730),
                            OperatingSystem = 0,
                            Price = 821.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.NewsPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'4', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NewsPost");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Google Cloud has brokered another partnership in its exploration of blockchain technologies, with the company joining the enterprise program of blockchain-based video delivery network Theta Labs. Google has joined the grandly-named Enterprise Validator Program, alongside Binance, Blockchain Ventures, and Gumi, which ‘allows enterprises to validate transactions in accordance with Theta’s underlying consensus protocol’, in its own words. Theta’s business case is to broadly put together a decentralised content delivery network (CDN), which will aim to solve the problems of combining high quality data throughput with no buffering, as well as giving more revenues to content creators rather than arbiters. Blockchain comes in through what the company calls ‘Theta fuel’ – tokens on which a value exchange is based between viewer and video platform. Theta and its partners in the media and entertainment, telecom, technology and gaming industries thus provide a high performance decentralised micropayment network that scales to millions of concurrent video viewers,” Theta wrote in a Medium post.  Google Cloud’s role will be to provide ‘stability, reliability and security’ to the Theta network, in the company’s words. Distributed ledger technology enables new business models that potentially transform the global digital economy, including the media and entertainment industry, said Allen Day, Google Cloud developer advocate. We look forward to participating as an enterprise validator, and to providing Google Cloud infrastructure in support of Theta’s long-term mission and future growth.",
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 681, DateTimeKind.Local).AddTicks(6340),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 681, DateTimeKind.Local).AddTicks(6380),
                            Title = "Google Cloud teams up with Theta Labs for blockchain-based video delivery"
                        },
                        new
                        {
                            Id = 2,
                            Content = "The coronavirus pandemic has magnified the importance of cloud-based technologies in major, life-altering ways and ushered in a new paradigm. Before COVID-19, experts projected the worldwide public cloud services market would jump by 17% this year, reaching $266.4 million. Software as a service is the largest segment within that market, but the second-largest — infrastructure as a service — claims the fastest growth rate.A number of factors are driving businesses to choose the cloud as the standard for applications, data, and storage. They migrate to gain flexible computing power, to lower the cost of backup/recovery, or to turn capital expenses into operational costs. Beyond any single benefit, however, companies migrate to facilitate organisational change in ways that only the cloud can offer.Take artificial intelligence as just one example. Companies that have already implemented AI saw an uptick in revenue, and 44% experienced a reduction in costs. Executives across industries want (and need) to use this technology effectively, and that’s possible from a technical and logistical standpoint only if the technology runs out of the cloud. To put it simply, the cloud is where the future happens, meaning companies either migrate or get left behind.",
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 681, DateTimeKind.Local).AddTicks(8360),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 681, DateTimeKind.Local).AddTicks(8380),
                            Title = "Covid-19 has hastened cloud migration – but don’t move without a plan"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Cloud providers need to proactively support their customers through the tail end of the Covid-19 pandemic. They can do this by demonstrating the strength and adaptability of their service offerings. Covid-19 has left many organisations unsure if their business continuity strategy is sufficiently robust, particularly when it comes to cloud services. The reliance on videoconferencing and collaboration tools has stressed the limits of back-end supporting services, while also increasing network traffic volume. However, cloud providers with robust and excess infrastructure, combined with disaster recovery plans to respond to such a crisis, are successfully managing in this new normal. As IT leaders begin to consider longer-term cloud solutions to support the new portion of their workforce remaining remote, they are facing challenging questions about the resiliency and dependability of cloud services. At the same time as Covid-19 has pushed cloud to the spotlight, it has put providers in a unique position to reassure customers of their strength and adaptability.The providers who will fail at this time are the ones still tackling the debate of on-premises data centres vs cloud. Customers are now asking about the adaptability of their current cloud service that they have been forced to adopt if they decided to continue using it post pandemic.",
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 681, DateTimeKind.Local).AddTicks(8420),
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 681, DateTimeKind.Local).AddTicks(8430),
                            Title = "Gartner: How and why cloud providers need to support their customers through Covid-19"
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'3', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 622, DateTimeKind.Local).AddTicks(5840),
                            Email = "admin@test.com",
                            FirstName = "Admin",
                            LastName = "Ad",
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 641, DateTimeKind.Local).AddTicks(1610),
                            Password = "10000.7mSNp+Oapzv2iVbiybMmSA==.TjfFGVah1ko7+nrYvgKIBwpJGGgVzRz2BcG24jUBMiE="
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 5, 31, 13, 22, 57, 641, DateTimeKind.Local).AddTicks(7310),
                            Email = "test@test.com",
                            FirstName = "Test",
                            LastName = "Testic",
                            Modified = new DateTime(2020, 5, 31, 13, 22, 57, 641, DateTimeKind.Local).AddTicks(7360),
                            Password = "10000.7mSNp+Oapzv2iVbiybMmSA==.TjfFGVah1ko7+nrYvgKIBwpJGGgVzRz2BcG24jUBMiE="
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.UserCloud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CloudDbSQLId")
                        .HasColumnType("integer");

                    b.Property<int?>("CloudFunctionId")
                        .HasColumnType("integer");

                    b.Property<int?>("CloudStorageId")
                        .HasColumnType("integer");

                    b.Property<int?>("CloudVMId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserInput")
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("CloudDbSQLId");

                    b.HasIndex("CloudFunctionId");

                    b.HasIndex("CloudStorageId");

                    b.HasIndex("CloudVMId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClouds");
                });

            modelBuilder.Entity("Oicar.Dal.Entities.UserCloud", b =>
                {
                    b.HasOne("Oicar.Dal.Entities.CloudDbSQL", "CloudDbSQL")
                        .WithMany("UserCloud")
                        .HasForeignKey("CloudDbSQLId");

                    b.HasOne("Oicar.Dal.Entities.CloudFunction", "CloudFunction")
                        .WithMany("UserCloud")
                        .HasForeignKey("CloudFunctionId");

                    b.HasOne("Oicar.Dal.Entities.CloudStorage", "CloudStorage")
                        .WithMany("UserCloud")
                        .HasForeignKey("CloudStorageId");

                    b.HasOne("Oicar.Dal.Entities.CloudVM", "CloudVM")
                        .WithMany("UserCloud")
                        .HasForeignKey("CloudVMId");

                    b.HasOne("Oicar.Dal.Entities.User", "User")
                        .WithMany("UserCloud")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
