// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oicar.Dal;

namespace Oicar.Dal.Migrations
{
    [DbContext(typeof(OicarContext))]
    partial class OicarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Oicar.Dal.Entities.CloudDbSQL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("AverageHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("BaskupSize")
                        .HasColumnType("integer");

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Instance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<int>("SQLServerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CloudSQL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 289, DateTimeKind.Local).AddTicks(6570),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 289, DateTimeKind.Local).AddTicks(6580),
                            Price = 45.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(400),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(410),
                            Price = 48.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 3,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(500),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(510),
                            Price = 41.0,
                            Ram = 1,
                            SQLServerType = 1
                        },
                        new
                        {
                            Id = 4,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(510),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(510),
                            Price = 24.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 5,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(520),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(520),
                            Price = 37.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 6,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(520),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(530),
                            Price = 36.0,
                            Ram = 1,
                            SQLServerType = 2
                        },
                        new
                        {
                            Id = 7,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(530),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(530),
                            Price = 27.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 8,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(540),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(540),
                            Price = 30.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 9,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(540),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(550),
                            Price = 31.0,
                            Ram = 1,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 10,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(550),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(550),
                            Price = 21.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 11,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(560),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(560),
                            Price = 20.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 12,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(560),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(560),
                            Price = 18.0,
                            Ram = 1,
                            SQLServerType = 3
                        },
                        new
                        {
                            Id = 13,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(570),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(570),
                            Price = 30.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 14,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(580),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(580),
                            Price = 27.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 15,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(580),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(580),
                            Price = 28.0,
                            Ram = 4,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 16,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(590),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(590),
                            Price = 38.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 17,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(590),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(600),
                            Price = 39.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 18,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(600),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(600),
                            Price = 40.0,
                            Ram = 8,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 19,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 0,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(610),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(610),
                            Price = 48.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 20,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 2,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(610),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(620),
                            Price = 47.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 21,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 1,
                            CloudProvider = 1,
                            CpuCores = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(620),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(620),
                            Price = 52.0,
                            Ram = 16,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 22,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 0,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(630),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(630),
                            Price = 59.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 23,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 2,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(630),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(640),
                            Price = 56.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 24,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 1,
                            CpuCores = 8,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(640),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(640),
                            Price = 57.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 25,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 0,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(650),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(650),
                            Price = 59.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 26,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 2,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(650),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(660),
                            Price = 56.0,
                            Ram = 32,
                            SQLServerType = 0
                        },
                        new
                        {
                            Id = 27,
                            AverageDaysPerWeek = 7,
                            AverageHoursPerDay = 24,
                            BaskupSize = 64,
                            CloudProvider = 1,
                            CpuCores = 16,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(660),
                            Instance = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 290, DateTimeKind.Local).AddTicks(660),
                            Price = 84.0,
                            Ram = 32,
                            SQLServerType = 0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExecutinPerRequestInMiliseconds")
                        .HasColumnType("integer");

                    b.Property<double>("ExecutionsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<int>("MemorySizeInMB")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CloudFunction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(5650),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 10000.0,
                            MemorySizeInMB = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(5660),
                            Price = 10.0
                        },
                        new
                        {
                            Id = 2,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7840),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 10000.0,
                            MemorySizeInMB = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7850),
                            Price = 12.0
                        },
                        new
                        {
                            Id = 3,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7900),
                            ExecutinPerRequestInMiliseconds = 10000,
                            ExecutionsPerMonth = 100000.0,
                            MemorySizeInMB = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7900),
                            Price = 9.0
                        },
                        new
                        {
                            Id = 4,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7910),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 10,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7910),
                            Price = 18.0
                        },
                        new
                        {
                            Id = 5,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7910),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 10,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7920),
                            Price = 20.0
                        },
                        new
                        {
                            Id = 6,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7920),
                            ExecutinPerRequestInMiliseconds = 50000,
                            ExecutionsPerMonth = 50000.0,
                            MemorySizeInMB = 10,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7920),
                            Price = 22.0
                        },
                        new
                        {
                            Id = 7,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7930),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 100,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7930),
                            Price = 44.0
                        },
                        new
                        {
                            Id = 8,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7930),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 100,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7940),
                            Price = 41.0
                        },
                        new
                        {
                            Id = 9,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7940),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 100,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7940),
                            Price = 39.0
                        },
                        new
                        {
                            Id = 10,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7950),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 1000,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7950),
                            Price = 44.0
                        },
                        new
                        {
                            Id = 11,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7950),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 1000,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7950),
                            Price = 41.0
                        },
                        new
                        {
                            Id = 12,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7960),
                            ExecutinPerRequestInMiliseconds = 20000,
                            ExecutionsPerMonth = 1000000.0,
                            MemorySizeInMB = 1000,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 287, DateTimeKind.Local).AddTicks(7960),
                            Price = 39.0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("ReadOperationsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<double>("WriteOperationsPerMonth")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CloudStorage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(4750),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(4760),
                            Price = 100.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 2,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(6950),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(6960),
                            Price = 54.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 16.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 3,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7020),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7020),
                            Price = 60.0,
                            ReadOperationsPerMonth = 1000000.0,
                            TotalAmount = 32.0,
                            WriteOperationsPerMonth = 1000000.0
                        },
                        new
                        {
                            Id = 4,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7030),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7030),
                            Price = 68.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 5,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7040),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7040),
                            Price = 88.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 6,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7040),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7040),
                            Price = 98.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 7,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7050),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7050),
                            Price = 112.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 8,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7050),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7060),
                            Price = 122.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 9,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7060),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7060),
                            Price = 135.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 10,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7070),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7070),
                            Price = 156.0,
                            ReadOperationsPerMonth = 2000000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 2000000.0
                        },
                        new
                        {
                            Id = 11,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7070),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7080),
                            Price = 159.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 1024.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 12,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7080),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7080),
                            Price = 76.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 13,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7080),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7090),
                            Price = 73.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 14,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7090),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7090),
                            Price = 79.0,
                            ReadOperationsPerMonth = 250000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 250000.0
                        },
                        new
                        {
                            Id = 15,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7100),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7100),
                            Price = 86.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 254.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 16,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7100),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7110),
                            Price = 99.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 17,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7110),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7110),
                            Price = 113.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 512.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 18,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7120),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7120),
                            Price = 183.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 19,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7120),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7130),
                            Price = 180.0,
                            ReadOperationsPerMonth = 4000000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 4000000.0
                        },
                        new
                        {
                            Id = 20,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7130),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7130),
                            Price = 167.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 21,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7140),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7140),
                            Price = 169.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 22,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7140),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7140),
                            Price = 160.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 23,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7150),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7150),
                            Price = 183.0,
                            ReadOperationsPerMonth = 10000.0,
                            TotalAmount = 2028.0,
                            WriteOperationsPerMonth = 10000.0
                        },
                        new
                        {
                            Id = 24,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7150),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7160),
                            Price = 68.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 25,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7160),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7160),
                            Price = 78.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 26,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7170),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7170),
                            Price = 65.0,
                            ReadOperationsPerMonth = 50000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 50000.0
                        },
                        new
                        {
                            Id = 27,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7170),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7180),
                            Price = 78.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 28,
                            CloudProvider = 0,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7180),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7180),
                            Price = 66.0,
                            ReadOperationsPerMonth = 500000.0,
                            TotalAmount = 128.0,
                            WriteOperationsPerMonth = 500000.0
                        },
                        new
                        {
                            Id = 29,
                            CloudProvider = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7180),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7190),
                            Price = 46.0,
                            ReadOperationsPerMonth = 125000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 125000.0
                        },
                        new
                        {
                            Id = 30,
                            CloudProvider = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7190),
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 283, DateTimeKind.Local).AddTicks(7190),
                            Price = 55.0,
                            ReadOperationsPerMonth = 125000.0,
                            TotalAmount = 64.0,
                            WriteOperationsPerMonth = 125000.0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.CloudVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("AverageHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("CloudProvider")
                        .HasColumnType("integer");

                    b.Property<int>("Core")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("InstanceNb")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<double>("Storage")
                        .HasColumnType("double precision");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CloudVM");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(3110),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(3120),
                            OperatingSystem = 1,
                            Price = 1500.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7200),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7220),
                            OperatingSystem = 1,
                            Price = 1250.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 3,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7310),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7320),
                            OperatingSystem = 0,
                            Price = 1650.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 4,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7320),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7320),
                            OperatingSystem = 0,
                            Price = 1400.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 5,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7330),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7330),
                            OperatingSystem = 1,
                            Price = 4000.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 6,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7330),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7340),
                            OperatingSystem = 1,
                            Price = 3800.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 7,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7340),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7340),
                            OperatingSystem = 0,
                            Price = 3600.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 8,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7350),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7350),
                            OperatingSystem = 0,
                            Price = 3750.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 9,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7350),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7360),
                            OperatingSystem = 1,
                            Price = 850.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 10,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7360),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7360),
                            OperatingSystem = 1,
                            Price = 900.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 11,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7370),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7370),
                            OperatingSystem = 0,
                            Price = 887.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 12,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 0,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7370),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7380),
                            OperatingSystem = 0,
                            Price = 800.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 13,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7380),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7380),
                            OperatingSystem = 1,
                            Price = 1509.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 14,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7390),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7390),
                            OperatingSystem = 1,
                            Price = 1350.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 15,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7390),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7400),
                            OperatingSystem = 0,
                            Price = 1652.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 16,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7400),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7400),
                            OperatingSystem = 0,
                            Price = 1389.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 17,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7410),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7410),
                            OperatingSystem = 1,
                            Price = 3800.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 18,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7410),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7420),
                            OperatingSystem = 1,
                            Price = 3901.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 19,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7420),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7420),
                            OperatingSystem = 0,
                            Price = 3609.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 20,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7430),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7430),
                            OperatingSystem = 0,
                            Price = 3759.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 21,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7430),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7430),
                            OperatingSystem = 1,
                            Price = 950.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 22,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7440),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7440),
                            OperatingSystem = 1,
                            Price = 909.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 23,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7450),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7450),
                            OperatingSystem = 0,
                            Price = 869.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 24,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 1,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7450),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7450),
                            OperatingSystem = 0,
                            Price = 809.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 25,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7460),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7460),
                            OperatingSystem = 1,
                            Price = 1499.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 26,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7460),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7470),
                            OperatingSystem = 1,
                            Price = 1359.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 27,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7470),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7470),
                            OperatingSystem = 0,
                            Price = 1656.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 28,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7480),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7480),
                            OperatingSystem = 0,
                            Price = 1379.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 29,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7480),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7490),
                            OperatingSystem = 1,
                            Price = 3790.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 30,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7490),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7490),
                            OperatingSystem = 1,
                            Price = 3911.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 31,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7500),
                            InstanceNb = 4,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7500),
                            OperatingSystem = 0,
                            Price = 3619.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 32,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7500),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7510),
                            OperatingSystem = 0,
                            Price = 3659.0,
                            Ram = 16,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 33,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7510),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7510),
                            OperatingSystem = 1,
                            Price = 944.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 34,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7520),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7520),
                            OperatingSystem = 1,
                            Price = 911.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        },
                        new
                        {
                            Id = 35,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7520),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7530),
                            OperatingSystem = 0,
                            Price = 919.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 1
                        },
                        new
                        {
                            Id = 36,
                            AverageDaysPerWeek = 6,
                            AverageHoursPerDay = 16,
                            CloudProvider = 2,
                            Core = 4,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7530),
                            InstanceNb = 1,
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 286, DateTimeKind.Local).AddTicks(7530),
                            OperatingSystem = 0,
                            Price = 821.0,
                            Ram = 8,
                            Storage = 256.0,
                            StorageType = 0
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 271, DateTimeKind.Local).AddTicks(290),
                            Email = "admin@test.com",
                            FirstName = "Admin",
                            LastName = "Ad",
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 280, DateTimeKind.Local).AddTicks(4340),
                            Password = "10000.7mSNp+Oapzv2iVbiybMmSA==.TjfFGVah1ko7+nrYvgKIBwpJGGgVzRz2BcG24jUBMiE="
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 5, 28, 23, 16, 55, 280, DateTimeKind.Local).AddTicks(7270),
                            Email = "test@test.com",
                            FirstName = "Test",
                            LastName = "Testic",
                            Modified = new DateTime(2020, 5, 28, 23, 16, 55, 280, DateTimeKind.Local).AddTicks(7290),
                            Password = "10000.7mSNp+Oapzv2iVbiybMmSA==.TjfFGVah1ko7+nrYvgKIBwpJGGgVzRz2BcG24jUBMiE="
                        });
                });

            modelBuilder.Entity("Oicar.Dal.Entities.UserCloud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CloudDbSQLId")
                        .HasColumnType("integer");

                    b.Property<int?>("CloudFunctionId")
                        .HasColumnType("integer");

                    b.Property<int?>("CloudStorageId")
                        .HasColumnType("integer");

                    b.Property<int?>("CloudVMId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserInput")
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("CloudDbSQLId");

                    b.HasIndex("CloudFunctionId");

                    b.HasIndex("CloudStorageId");

                    b.HasIndex("CloudVMId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClouds");
                });

            modelBuilder.Entity("Oicar.Dal.Entities.UserCloud", b =>
                {
                    b.HasOne("Oicar.Dal.Entities.CloudDbSQL", "CloudDbSQL")
                        .WithMany("UserCloud")
                        .HasForeignKey("CloudDbSQLId");

                    b.HasOne("Oicar.Dal.Entities.CloudFunction", "CloudFunction")
                        .WithMany("UserCloud")
                        .HasForeignKey("CloudFunctionId");

                    b.HasOne("Oicar.Dal.Entities.CloudStorage", "CloudStorage")
                        .WithMany("UserCloud")
                        .HasForeignKey("CloudStorageId");

                    b.HasOne("Oicar.Dal.Entities.CloudVM", "CloudVM")
                        .WithMany("UserCloud")
                        .HasForeignKey("CloudVMId");

                    b.HasOne("Oicar.Dal.Entities.User", "User")
                        .WithMany("UserCloud")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
